services:
  react-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-tests
    restart: 'no'
    ports:
      - 3000:3000/tcp
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules





